server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camino
    username: camino
    password: ${DB_PASSWORD:camino_local_pw}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always